name: Actions Workflow

on: [push]

jobs:
  runs-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        # git clone git@gitgub:$GITHUB_REPOSITORY
        # git checkout $GITHUB_SHA

      - name: Check Out files
        id: checkout
        uses: actions/checkout@v2

      - name: Files after Checkout 
        run: |
          pwd
          ls -a

      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: dino the dinasouraz

      - name: output Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"


