name: Kube-test

#on: [push, pull_request]
on:
  push:
  #schedule:
  #  - cron: "1 * * * *"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  runs-k8-job:
    runs-on: ubuntu-latest
    steps:

      - name: Kubectl commands
        run: |
          pwd
          ls -a
          kubectl get nodes
        #  echo $GITHUB_SHA
        #  echo $GITHUB_REPOSITORY
        #  echo $GITHUB_WORKSPACE
        #  echo "${{ github.token }}"
        #  echo "env variables"
        #  env
        #  git clone git@gitgub:$GITHUB_REPOSITORY
        #  git checkout $GITHUB_SHA

      - name: Check Out files
        id: checkout
        uses: actions/checkout@v2

      - name: Files after Checkout 
        run: |
          pwd
          ls -a