name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multi-line scrits
        run: |
          node -v
          ls 
          pwd
          npm -v
      - name: python-command
        run: |
          import platform
          print (platform.processor())
        shell: python
  new-windows-shell:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: show dir in powershell
        run: Get-Location
      - name: dir in bash
        run: pwd
        shell: bash
       

          

